services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: events_db
      MYSQL_USER: eventuser
      MYSQL_PASSWORD: eventpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "eventuser", "-peventpass"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: 